# Generated by Django 2.2.5 on 2019-11-15 22:06

import datetime
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('artist', models.CharField(blank=True, max_length=100, null=True)),
                ('universe', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_main', models.ImageField(upload_to=product.models.upload_image_path)),
                ('photo_1', models.ImageField(blank=True, upload_to=product.models.upload_image_path)),
                ('photo_2', models.ImageField(blank=True, upload_to=product.models.upload_image_path)),
                ('photo_3', models.ImageField(blank=True, upload_to=product.models.upload_image_path)),
                ('is_published', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
