# Generated by Django 2.2.5 on 2019-11-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
