# Generated by Django 2.2.5 on 2019-12-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191115_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='slug',
            field=models.SlugField(blank=True, max_length=600, unique=True),
        ),
    ]
