# Generated by Django 2.2.5 on 2019-12-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191201_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
