# Generated by Django 2.2.5 on 2019-12-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20191201_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='category',
            field=models.CharField(choices=[('DC', 'DC Comics'), ('MARVEL', 'Marvel Comics'), ('ACCESSORIES', 'Accessories'), ('OTHE', 'Senior')], default='Unnamed stuff!', max_length=50),
        ),
    ]
