# Generated by Django 2.2.5 on 2019-12-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_comic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='category',
            field=models.CharField(choices=[('DC', 'DC Comics'), ('MARVEL', 'Marvel Comics'), ('ACCESSORIES', 'Accessories'), ('OTHER', 'Other'), ('NO-CAT', 'No cat')], default='NO-CAT', max_length=50),
        ),
    ]
