# Generated by Django 2.2.5 on 2019-12-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20191214_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='category',
            field=models.CharField(choices=[('DC', 'dc'), ('MARVEL', 'marvel'), ('ACCESSORIES', 'accessories'), ('OTHER', 'other'), ('NO-CAT', 'nocat')], default='NO-CAT', max_length=50),
        ),
    ]
