const NotificationActionTypes = {
    ADD_CART_NOTIFICATION_DISPLAY: "ADD_CART_NOTIFICATION_DISPLAY",
    ADD_CART_NOTIFICATION_REMOVE: "ADD_CART_NOTIFICATION_REMOVE",
    REMOVE_CART_NOTIFICATION_DISPLAY: "REMOVE_CART_NOTIFICATION_DISPLAY",
    REMOVE_CART_NOTIFICATION_REMOVE: "REMOVE_CART_NOTIFICATION_REMOVE"

}

export default NotificationActionTypes
